<h3>QUALITY & AUTHENTICITY</h3>
<strong>Quality</strong>
                                    <p>Our fashion experts carefully evaluate each item we receive and determine its quality. We are very strict about quality and do not accept anything that does not meet our stringent quality requirements. Items with stains, tears, fading or pilling are immediately rejected.
                                        To learn more about our Quality Standards, <a href="http://www.rekinza.com/authentication">click here</a>.</p>
                                    
                                    <strong>Authenticity</strong>
                                    <p>We draw from the expertise of our merchandising and authentication team which evaluates each item for brand-specific authenticity details, including materials, stitching, name plates, hardware, serial numbers and holograms. Thus, everything passes through our strict authenticity tests before it is approved and uploaded on our website.
                                        To learn more about our Authentication Process, <a href="http://www.rekinza.com/buyer-protection">click here</a>.</p>