<?php
if ($this->isPageWidgetsEnabled ()) {
	$paramData = $this->getWidgetParams ();
	$mid = $this->getMID ();

	$currencyFactor = "1.0";
	$currencySymbol = "";
	if($this->isCurrencyChanged()){	
		$currencyFactor = $this->getCurrencyRate();
		$currencySymbol = $this->getCurrentCurrencySymbol();
	}
	$baseUrl = Mage::getBaseUrl();
	$tmRegion = $this->getTmRegion();
	?>
<script type="text/javascript">
//<![CDATA[
	TMJS.init({mid:'<?php echo $mid; ?>',domain:'<?php echo $tmRegion; ?>',conversionFactor: <?php echo $currencyFactor; ?>, symbol: '<?php echo $currencySymbol; ?>', baseUrl: '<?php echo $baseUrl; ?>'});
	TMJS.generateWidgets({<?php echo $paramData; ?>});
//]]>
</script>
<?php
}
?>