<div class="pickup">
<div class="col-lg-6 col-lg-offset-3">
  <div class="pickup-title">
        <h1 class="pickup-h1" style="text-transform:uppercase;">Request A Return</h1>
        <h2 class="pickup-h2">We are sorry the item was not a perfect fit for you.</h2> 
		<h2 class="pickup-h2">Please fill the form below to initiate your returns.</h2>
		<img src="http://www.rekinza.com/images/seller-emails/returns-requested.png" width=100%/>
    </div>
</div> 
    
<form id="return_form" method="post" action="<?php echo $this->getUrl("thredshare_returns/returns/requestreturns");?>">
<div class="col-lg-6 col-lg-offset-3">
<div class="pickup-box">
<h3 class="pickup-h3"> Reason for Return </h3>
<select class = "required "name ="reason" id = "reason">
	<option value="" disabled="disabled" selected="selected">Reason for Return</option>
	<option value ="fit_too_big">Fit (Too Big)</option>
	<option value ="fit_too_small">Fit (Too Small)</option>
	<option value ="website_mismatch">Product did not match website data</option>
	<option value ="expecation_mismatch">Product did not match my expectation</option>
	<option value ="incorrect_product">Incorrect product received</option>
	<option value ="others">Others</option>
</select>
</div>
<div class="pickup-box">
<h3 class="pickup-h3"> Tell Us About You & Your Order </h3>
<input class="required" type="text" name="email_id" id="email_id" placeholder="Email ID" onchange ="show_order_id_field();"/>
<input class="required" type="text" name ="order_number" id ="order_number" placeholder="Order ID" onkeypress='validate(event)'/>
<input class="required" type="text" name="items" id="items" placeholder="Item(s) to return"/>
<input class="required" type="text" name="mobile" placeholder="Mobile Phone Number" onkeypress='validate(event)'/>
</div>
<div class="pickup-box">
<h3 class="pickup-h3"> When & Where Can We Get The Item/s Picked </h3>
<input class="required number" type="text" name="date" id="datepicker" placeholder="Pickup Date"/>
<input class="required" type="text" name="address1" placeholder="Address Line 1"/>
<input class="required" type="text" name="address2" placeholder="Address Line 2"/>
<input class="required" type="text" name="city" placeholder="City"/>
<input class="required" type="text" name="state" placeholder="State"/>
<input class="required number" type="text" name="pincode" placeholder="Pin Code"/>
<!--<br>Pickup Start Time
<input class="required number" type="time" name="start_time" id="start_time"/>
<br>Pickup End Time
<input class="required number" type="time" name="end_time" id="end_time"/>-->
</div>
<!--<div class="pickup-box">
<h3 class="pickup-h3"> How would you like your refund? </h3>
<br>Refund Mode</br>
<select name ="refund_mode" id = "refund_mode" onChange="changeTextBox();">-->
<!----Auto fill based on AJAX call---->
<!--</select>
<br>
<input type="text" name="acc_holders_name" id ="acc_holders_name" placeholder="Account Holder's Name" hidden = "true"/>
<input type="text" name="acc_number" id ="acc_number" placeholder="Account Number" hidden = "true" onkeypress='validate(event)'/>
<input type="text" name="ifsc_code" id ="ifsc_code" placeholder="IFSC Code" hidden = "true"/>

</div>-->
<div class="clear"></div>
<div class="pickup-title" style="text-align:left;font-size:14px; line-height:120%; ">
<p>Once we receive and check the returns in our warehouse, we will credit your account with the relevant Kinza Cash. </p>

<p>You can use your Kinza Cash to:</p>
<ul style="list-style-type: square; text-indent: 10px;">
<li>Buy something on <a href="http://www.rekinza.com/shop" target="_blank" style="color:#f05865">Rekinza</a></li>
<li>Cash out via bank transfer</li>
<li>Donate to our charity partner</li>
</ul>
<p>&nbsp;</p>
<p >Please note that your Kinza Cash does not expire.</p>
</div>
<button type="button" onclick="submitReturnForm();" title="Submit" class="button" id ="return_submit"><span><span>Submit</span></span></button>
</div>
</form>
</div>
<script>

function submitReturnForm(){
isSuc=true;
/*jQuery('.pickup .number').each(function(){
if (!(/[0-9]+/.test(jQuery(this).val()))){
alert(jQuery(this).attr('placeholder')+" should be a number");
isSuc=false;
return false;
}
});*/
if (!isSuc){
return;
}
jQuery('.pickup .required').each(function(){
if (!(/.+/.test(jQuery(this).val()))){
alert(jQuery(this).attr('placeholder')+" is required");
isSuc=false;
return false;
}
});
if (!isSuc){
return;
}
jQuery('.pickup .pincode').each(function(){
if (!(/[0-9]{10,10}/.test(jQuery(this).val()))){
alert("Please enter a valid pincode no.");
isSuc=false;
return false;
}
});
if (!isSuc){
return;
}

jQuery('#return_form').submit();

}
function DisableSunday(date) {
 
  var day = date.getDay();
 // If day == 0 then it is Sunday
 if (day == 0) {
 
 return [false] ; 
 
 } else { 
 
 return [true] ;
 }
  
}

jQuery(document).ready(function(){
jQuery('#datepicker').datepicker({
	beforeShowDay: DisableSunday,
	minDate:new Date((new Date()).getTime()+2*86400000)
	});
});

/*************Display order ID field if email ID is not null******************/
function show_order_id_field()
{
	console.log("ha");
	var email_input = document.getElementById('email_id').value;
	
	strlen = email_input.length;
		
	if (Number(strlen) > 0)
	{
		console.log("hi");
		document.getElementById('order_number').removeAttribute("disabled");
	}
	else
	{
		console.log("ho");
		document.getElementById('order_number').setAttribute("disabled", true);
	}
}

/*************Check if order ID filled is valid******************/
( function($) {	   
jQuery(document).ready(
	function($)
	{
		jQuery('#order_number').change(
			function()
			{
				jQuery.ajax({
				type:'POST',
				
				url:"/backend/returns/returns_order_id_validate.php",
				data:
				{
					'order_number':jQuery('#order_number').val(),
					'email_id':jQuery('#email_id').val()
				},
				async: false,
				
				success:function(message)
				{
					if(!jQuery.trim(message)) 
					{ 
						document.getElementById('return_submit').hidden = false;//Submit button can be enabled
					}
					else
					{
						alert(message);
						document.getElementById('return_submit').hidden = true; //Submit button to be disabled
						
					}
				}
				});
			
			}
		);		
	}
);
})(jQuery);



/*************Fill refund types based on order ID******************/
/*( function($) {	   
$(document).ready(
	function($)
	{
		$('#order_number').change(
			function()
			{
				$.ajax({
				type:'POST',
				url:"/backend/returns/returns_payment_mode_check.php",
				data:
				{
					'order_number':$('#order_number').val()
				},
				async: false,
				success:function(message)
				{
					$('#refund_mode').html(message);
				}
				});
			
			}
		);		
	}
);
})(jQuery);*/

/********************* Display bank transfer details boxes only if refund mode selected is Bank Transfer*********************/
/*function changeTextBox() {
    var comp = document.getElementById('refund_mode');
    if(comp.value=='Bank Transfer')
	{  
		document.getElementById('acc_holders_name').hidden=false;
		document.getElementById('acc_number').hidden=false;
		document.getElementById('ifsc_code').hidden=false;
	}
    else
	{
		document.getElementById('acc_holders_name').hidden=true;
		document.getElementById('acc_number').hidden=true;
		document.getElementById('ifsc_code').hidden=true;
	}

	}*/
/********************* Validate numeric entry in form field*********************/
function validate(evt) 
{
	var theEvent = evt || window.event;
	var key = theEvent.keyCode || theEvent.which;
	key = String.fromCharCode( key );
	var regex = /[0-9]|\./;
	if( !regex.test(key) ) 
	{
		theEvent.returnValue = false;
		if(theEvent.preventDefault) theEvent.preventDefault();
	}
}
	
	
</script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>